[package]
name = "bqsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.1"
structopt = "0.3.25"
rand = "0.8.4"
